function R = Rotation_Euler(fi,theta,psi)
%     R_psi = [cos(psi) sin(psi) 0;...
%             -sin(psi) cos(psi) 0;...
%             0 0 1];
%     R_theta = [1 0 0;...
%              0 cos(theta) sin(theta);...
%             0 -sin(theta) cos(theta)];
%     R_fi = [cos(fi) sin(fi) 0;...
%             -sin(fi) cos(fi) 0;...
%             0 0 1];
    %x
    R_psi = [1 0 0;0 cos(psi) -sin(psi);0 sin(psi) cos(psi)];
    %y
    R_theta = [cos(theta)  0 sin(theta);0 1 0;-sin(theta) 0 cos(theta)];
    %z
    R_fi = [cos(fi) -sin(fi) 0;sin(fi) cos(fi) 0;0 0 1];
    R = R_fi*R_theta*R_psi;
end